ARG MP_VERSION=3.4.0

FROM node:20-alpine

# libs needed to build the masterportal
RUN apk update && apk add --no-cache --virtual .gyp \
    make \
    g++ \
    pkgconfig \
    pixman-dev \
    cairo-dev \
    pango-dev \
    python3 \
    git \
    libc6-compat

RUN git clone https://bitbucket.org/geowerkstatt-hamburg/masterportal.git

WORKDIR /masterportal
RUN git checkout ${MP_VERSION}

COPY ./portalconfig/package.json ./

# install dependencies
RUN npm install

# disable host check in webpack in order to get nginx proxy working together with webpack
RUN sed -i 's;port: 9001,;port: 9001,disableHostCheck: true,;' devtools/webpack.dev.js
# disable https to get hot reload running again
RUN sed -i 's;https: true,;https: false,;' devtools/webpack.dev.js

WORKDIR /masterportal/addons/simulationTool
RUN npm install

WORKDIR /masterportal

# run masterportal
ENTRYPOINT ["npm", "run", "start", "--", "--host", "0.0.0.0"]